[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../common"}
x86_64 = "0.14.10"
spin = "0.9.8"
uart_16550 = "0.2.18"
uefi = "0.18.0"
elf_rs = "0.3.0"
